development: &common_settings
  autorequire:
    directories: [/resource]
  resource_methods: [get, post, put, patch, delete, options]

test:
  <<: *common_settings
  autorequire:
    directories: [ /resource, /test/resource]

production:
  <<: *common_settings
