development: &common_settings
  autorequire:
    directories: [/lib, /resource]
  resource_methods: [get, post, put, patch, delete, options]

test:
  <<: *common_settings
  autorequire:
    directories: [/lib, /resource, /test/resource]

production:
  <<: *common_settings
